apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: cityflow
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/part-of: cityflow
data:
  PORT: "5000"
  TICK_INTERVAL_MINUTES: "360"
  ADMIN_EMAIL: "admin@sizops.co.il"
  DISCORD_BOT_API_URL: "http://cityflow-discord-bot:5001"
