apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cityflow

resources:
  - namespace.yml
  - config/backend-configmap.yml
  - config/discord-bot-configmap.yml
  - config/networkpolicy-deny-all.yml
  - mongodb/statefulset.yml
  - mongodb/service.yml
  - mongodb/networkpolicy.yml
  - backend/deployment.yml
  - backend/service.yml
  - backend/networkpolicy.yml
  - frontend/deployment.yml
  - frontend/service.yml
  - frontend/networkpolicy.yml
  - discord-bot/deployment.yml
  - discord-bot/networkpolicy.yml
  - ingress/middleware.yml
  - ingress/ingress.yml
