apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cityflow

resources:
  - namespace.yml
  - config/backend-configmap.yml
  - config/backend-secrets.yml
  - mongodb/statefulset.yml
  - mongodb/service.yml
  - backend/deployment.yml
  - backend/service.yml
  - frontend/deployment.yml
  - frontend/service.yml
  - ingress/ingress.yml
