export const AUCTION_CONFIG = {
  durations: {
    short: 1,
    medium: 4,
    long: 8,
    extended: 16,
  },
  endingDurationTicks: 2,
  antiSnipingTicks: 1,
  antiSnipingThresholdTicks: 2,
  minBidIncrementPercent: 5,
  bankAuctionIntervalTicks: 8,
  maxActiveAuctionsPerPlayer: 10,
  maxActiveBidsPerPlayer: 20,
  maxWatchlistPerPlayer: 50,
  playerListingFeePercent: 5,
  playerSoldCommissionPercent: 3,
  featuredMinBids: 3,
  featuredEndingTicks: 3,
  endingSoonTicks: 3,
  generation: {
    baseUpcoming: 2,
    upcomingPerPlayer: 0.03,
    maxUpcoming: 12,
    minActive: 2,
    activePerPlayer: 0.04,
    maxActive: 15,
    bankAuctionIntervalTicks: 4,
  },
  featuredScoring: {
    valueWeight: 30,
    bidsWeight: 25,
    watchersWeight: 20,
    rarityBonus: { uncommon: 0, rare: 15, legendary: 30 },
    endingSoonBonus: 20,
  },
  companyBid: {
    // Maximum company voting period (wall-clock) for an auction-bid proposal.
    votingDurationMs: 6 * 60 * 60 * 1000,
    // A proposal stuck in `resolving` for longer than this is considered
    // abandoned by a crashed worker and becomes eligible for safe recovery.
    resolutionStaleMs: 10 * 60 * 1000,
    // How often the scheduler scans for stale resolutions.
    recoveryIntervalMs: 60 * 1000,
  },
  cacheTTL: {
    featured: 30,
    analytics: 60,
    list: 20,
    detail: 15,
    reputation: 120,
    watchlist: 30,
  },
};

export const AUCTION_PROPERTY_POOL = [
  {
    name: 'Historic Mansion',
    type: 'house',
    propertyRating: 'luxury',
    basePriceMin: 500000,
    basePriceMax: 2000000,
    rarity: 'rare',
  },
  {
    name: 'Waterfront Penthouse',
    type: 'apartment',
    propertyRating: 'elite',
    basePriceMin: 800000,
    basePriceMax: 3000000,
    rarity: 'rare',
  },
  {
    name: 'Downtown Office Tower',
    type: 'commercial',
    propertyRating: 'premium',
    basePriceMin: 1000000,
    basePriceMax: 5000000,
    rarity: 'legendary',
  },
  {
    name: 'Luxury Resort Complex',
    type: 'commercial',
    propertyRating: 'elite',
    basePriceMin: 2000000,
    basePriceMax: 8000000,
    rarity: 'legendary',
  },
  {
    name: 'Prime Retail Center',
    type: 'commercial',
    propertyRating: 'premium',
    basePriceMin: 700000,
    basePriceMax: 3000000,
    rarity: 'rare',
  },
  {
    name: 'Exclusive Villa Estate',
    type: 'house',
    propertyRating: 'elite',
    basePriceMin: 1500000,
    basePriceMax: 6000000,
    rarity: 'legendary',
  },
  {
    name: 'Boutique Hotel',
    type: 'commercial',
    propertyRating: 'premium',
    basePriceMin: 600000,
    basePriceMax: 2500000,
    rarity: 'rare',
  },
  {
    name: 'Industrial Complex',
    type: 'commercial',
    propertyRating: 'improved',
    basePriceMin: 400000,
    basePriceMax: 1500000,
    rarity: 'uncommon',
  },
  {
    name: 'Skyline Tower',
    type: 'apartment',
    propertyRating: 'premium',
    basePriceMin: 900000,
    basePriceMax: 4000000,
    rarity: 'rare',
  },
  {
    name: 'Heritage Building',
    type: 'house',
    propertyRating: 'premium',
    basePriceMin: 300000,
    basePriceMax: 1200000,
    rarity: 'uncommon',
  },
  {
    name: 'Iconic Skyscraper',
    type: 'commercial',
    propertyRating: 'elite',
    basePriceMin: 3000000,
    basePriceMax: 10000000,
    rarity: 'legendary',
  },
  {
    name: 'Marina Complex',
    type: 'commercial',
    propertyRating: 'luxury',
    basePriceMin: 2500000,
    basePriceMax: 7000000,
    rarity: 'legendary',
  },
  {
    name: 'Private Island Resort',
    type: 'commercial',
    propertyRating: 'elite',
    basePriceMin: 5000000,
    basePriceMax: 15000000,
    rarity: 'legendary',
  },
  {
    name: 'Historic Castle',
    type: 'house',
    propertyRating: 'elite',
    basePriceMin: 2000000,
    basePriceMax: 8000000,
    rarity: 'legendary',
  },
  {
    name: 'Landmark Building',
    type: 'commercial',
    propertyRating: 'luxury',
    basePriceMin: 1500000,
    basePriceMax: 5000000,
    rarity: 'legendary',
  },
  {
    name: 'Luxury Penthouse Collection',
    type: 'apartment',
    propertyRating: 'elite',
    basePriceMin: 1200000,
    basePriceMax: 4500000,
    rarity: 'rare',
  },
  {
    name: 'Cinema & Entertainment Complex',
    type: 'commercial',
    propertyRating: 'premium',
    basePriceMin: 800000,
    basePriceMax: 3000000,
    rarity: 'rare',
  },
  {
    name: 'Eco-Luxury Tower',
    type: 'apartment',
    propertyRating: 'elite',
    basePriceMin: 1800000,
    basePriceMax: 6000000,
    rarity: 'legendary',
  },
];

export const RARITY_WEIGHTS = {
  uncommon: 40,
  rare: 40,
  legendary: 20,
};
