export const MISSION_CATEGORIES = [
  'beginner',
  'property',
  'income',
  'networth',
  'geographic',
  'development',
  'banking',
  'auction',
  'company',
  'district',
  'intelligence',
  'social',
  'marketplace',
  'stocks',
  'exploration',
  'engagement',
  'daily',
  'weekly',
  'seasonal',
  'event',
];

export const MISSION_DIFFICULTIES = {
  easy: { label: 'Easy', xpMultiplier: 1, balanceMultiplier: 1 },
  medium: { label: 'Medium', xpMultiplier: 2, balanceMultiplier: 2 },
  hard: { label: 'Hard', xpMultiplier: 4, balanceMultiplier: 4 },
  expert: { label: 'Expert', xpMultiplier: 8, balanceMultiplier: 8 },
  legendary: { label: 'Legendary', xpMultiplier: 16, balanceMultiplier: 16 },
};

export const MISSION_TYPES = ['permanent', 'daily', 'weekly', 'seasonal', 'event'];

export const MISSION_DEFINITIONS = [
  // ─── BEGINNER MISSIONS ───────────────────────────────
  {
    id: 'first_property',
    name: 'First Steps',
    description: 'Purchase your first property',
    category: 'beginner',
    difficulty: 'easy',
    type: 'permanent',
    order: 1,
    chainId: 'property_chain',
    chainOrder: 1,
    condition: { type: 'properties_owned', target: 1 },
    rewards: { xp: 50, balance: 5000 },
    icon: '🏠',
    unlocked: true,
  },
  {
    id: 'first_rent',
    name: 'Passive Income',
    description: 'Collect your first rent payment',
    category: 'beginner',
    difficulty: 'easy',
    type: 'permanent',
    order: 2,
    condition: { type: 'total_rent_collected', target: 1 },
    rewards: { xp: 50, balance: 5000 },
    icon: '💰',
    unlocked: true,
  },
  {
    id: 'first_upgrade',
    name: 'Renovation Rookie',
    description: 'Upgrade a property for the first time',
    category: 'beginner',
    difficulty: 'easy',
    type: 'permanent',
    order: 3,
    chainId: 'upgrade_chain',
    chainOrder: 1,
    condition: { type: 'total_upgrades', target: 1 },
    rewards: { xp: 75, balance: 7500 },
    icon: '🔧',
    unlocked: true,
  },
  {
    id: 'first_sell',
    name: 'Flipper',
    description: 'Sell your first property',
    category: 'beginner',
    difficulty: 'easy',
    type: 'permanent',
    order: 4,
    condition: { type: 'total_properties_sold', target: 1 },
    rewards: { xp: 75, balance: 10000 },
    icon: '💸',
    unlocked: true,
  },
  {
    id: 'first_auction',
    name: 'Auction Rookie',
    description: 'Purchase your first auction property',
    category: 'beginner',
    difficulty: 'easy',
    type: 'permanent',
    order: 5,
    chainId: 'auction_chain',
    chainOrder: 1,
    condition: { type: 'auctions_won', target: 1 },
    rewards: { xp: 100, balance: 15000 },
    icon: '🔨',
    unlocked: true,
  },

  // ─── PROPERTY MISSIONS ───────────────────────────────
  {
    id: 'own_5_properties',
    name: 'Small Portfolio',
    description: 'Own 5 properties',
    category: 'property',
    difficulty: 'easy',
    type: 'permanent',
    order: 10,
    chainId: 'property_chain',
    chainOrder: 2,
    prerequisiteMissionId: 'first_property',
    condition: { type: 'properties_owned', target: 5 },
    rewards: { xp: 200, balance: 25000 },
    icon: '🏘️',
  },
  {
    id: 'own_10_properties',
    name: 'Growing Empire',
    description: 'Own 10 properties',
    category: 'property',
    difficulty: 'medium',
    type: 'permanent',
    order: 11,
    chainId: 'property_chain',
    chainOrder: 3,
    prerequisiteMissionId: 'own_5_properties',
    condition: { type: 'properties_owned', target: 10 },
    rewards: { xp: 500, balance: 75000 },
    icon: '🏗️',
  },
  {
    id: 'own_25_properties',
    name: 'Real Estate Mogul',
    description: 'Own 25 properties',
    category: 'property',
    difficulty: 'hard',
    type: 'permanent',
    order: 12,
    chainId: 'property_chain',
    chainOrder: 4,
    prerequisiteMissionId: 'own_10_properties',
    condition: { type: 'properties_owned', target: 25 },
    rewards: { xp: 1500, balance: 250000, title: 'Mogul' },
    icon: '🏢',
  },
  {
    id: 'own_100_properties',
    name: 'Property Empire',
    description: 'Own 100 properties',
    category: 'property',
    difficulty: 'legendary',
    type: 'permanent',
    order: 13,
    chainId: 'property_chain',
    chainOrder: 5,
    prerequisiteMissionId: 'own_25_properties',
    condition: { type: 'properties_owned', target: 100 },
    rewards: { xp: 10000, balance: 2000000, title: 'Property Emperor', badge: 'property_empire' },
    icon: '👑',
  },
  {
    id: 'own_legendary_property',
    name: 'Legend Collector',
    description: 'Own a Legendary rated property',
    category: 'property',
    difficulty: 'medium',
    type: 'permanent',
    order: 14,
    condition: { type: 'own_legendary_property', target: 1 },
    rewards: { xp: 500, balance: 50000, badge: 'legend_collector' },
    icon: '⭐',
  },

  // ─── INCOME MISSIONS ────────────────────────────────
  {
    id: 'income_1k',
    name: 'Steady Earner',
    description: 'Reach $1,000 monthly income',
    category: 'income',
    difficulty: 'easy',
    type: 'permanent',
    order: 20,
    chainId: 'income_chain',
    chainOrder: 1,
    condition: { type: 'monthly_income', target: 1000 },
    rewards: { xp: 100, balance: 10000 },
    icon: '💵',
  },
  {
    id: 'income_10k',
    name: 'Rising Income',
    description: 'Reach $10,000 monthly income',
    category: 'income',
    difficulty: 'medium',
    type: 'permanent',
    order: 21,
    chainId: 'income_chain',
    chainOrder: 2,
    prerequisiteMissionId: 'income_1k',
    condition: { type: 'monthly_income', target: 10000 },
    rewards: { xp: 400, balance: 50000 },
    icon: '💶',
  },
  {
    id: 'income_100k',
    name: 'High Roller',
    description: 'Reach $100,000 monthly income',
    category: 'income',
    difficulty: 'hard',
    type: 'permanent',
    order: 22,
    chainId: 'income_chain',
    chainOrder: 3,
    prerequisiteMissionId: 'income_10k',
    condition: { type: 'monthly_income', target: 100000 },
    rewards: { xp: 1500, balance: 200000, title: 'High Roller' },
    icon: '💷',
  },
  {
    id: 'income_1m',
    name: "Millionaire's Income",
    description: 'Reach $1,000,000 monthly income',
    category: 'income',
    difficulty: 'expert',
    type: 'permanent',
    order: 23,
    chainId: 'income_chain',
    chainOrder: 4,
    prerequisiteMissionId: 'income_100k',
    condition: { type: 'monthly_income', target: 1000000 },
    rewards: { xp: 5000, balance: 1000000, title: 'Income Titan', badge: 'income_titan' },
    icon: '🏦',
  },

  // ─── NET WORTH MISSIONS ─────────────────────────────
  {
    id: 'networth_1m',
    name: 'Millionaire',
    description: 'Reach $1M net worth',
    category: 'networth',
    difficulty: 'easy',
    type: 'permanent',
    order: 30,
    chainId: 'networth_chain',
    chainOrder: 1,
    condition: { type: 'net_worth', target: 1000000 },
    rewards: { xp: 200, balance: 25000 },
    icon: '💎',
  },
  {
    id: 'networth_10m',
    name: 'Multi-Millionaire',
    description: 'Reach $10M net worth',
    category: 'networth',
    difficulty: 'medium',
    type: 'permanent',
    order: 31,
    chainId: 'networth_chain',
    chainOrder: 2,
    prerequisiteMissionId: 'networth_1m',
    condition: { type: 'net_worth', target: 10000000 },
    rewards: { xp: 1000, balance: 150000 },
    icon: '💰',
  },
  {
    id: 'networth_100m',
    name: 'Tycoon',
    description: 'Reach $100M net worth',
    category: 'networth',
    difficulty: 'hard',
    type: 'permanent',
    order: 32,
    chainId: 'networth_chain',
    chainOrder: 3,
    prerequisiteMissionId: 'networth_10m',
    condition: { type: 'net_worth', target: 100000000 },
    rewards: { xp: 5000, balance: 1000000, title: 'Tycoon' },
    icon: '🏆',
  },
  {
    id: 'networth_1b',
    name: 'Billionaire',
    description: 'Reach $1B net worth',
    category: 'networth',
    difficulty: 'legendary',
    type: 'permanent',
    order: 33,
    chainId: 'networth_chain',
    chainOrder: 4,
    prerequisiteMissionId: 'networth_100m',
    condition: { type: 'net_worth', target: 1000000000 },
    rewards: { xp: 20000, balance: 10000000, title: 'Billionaire', badge: 'billionaire' },
    icon: '🌐',
  },

  // ─── GEOGRAPHIC EXPANSION MISSIONS ──────────────────
  {
    id: 'geo_first_city',
    name: 'New Horizons',
    description: 'Own property in a different city',
    category: 'geographic',
    difficulty: 'easy',
    type: 'permanent',
    order: 40,
    condition: { type: 'unique_cities', target: 2 },
    rewards: { xp: 150, balance: 15000 },
    icon: '🌍',
  },
  {
    id: 'geo_3_cities',
    name: 'World Traveler',
    description: 'Own properties in 3 different cities',
    category: 'geographic',
    difficulty: 'medium',
    type: 'permanent',
    order: 41,
    chainId: 'geo_chain',
    chainOrder: 1,
    condition: { type: 'unique_cities', target: 3 },
    rewards: { xp: 500, balance: 50000, title: 'World Traveler' },
    icon: '✈️',
  },
  {
    id: 'geo_5_cities',
    name: 'Global Investor',
    description: 'Own properties in 5 different cities',
    category: 'geographic',
    difficulty: 'hard',
    type: 'permanent',
    order: 42,
    chainId: 'geo_chain',
    chainOrder: 2,
    prerequisiteMissionId: 'geo_3_cities',
    condition: { type: 'unique_cities', target: 5 },
    rewards: { xp: 1500, balance: 200000, title: 'Global Investor', badge: 'global_investor' },
    icon: '🌏',
  },
  {
    id: 'geo_all_cities',
    name: 'World Conqueror',
    description: 'Own properties in all cities',
    category: 'geographic',
    difficulty: 'legendary',
    type: 'permanent',
    order: 43,
    chainId: 'geo_chain',
    chainOrder: 3,
    prerequisiteMissionId: 'geo_5_cities',
    condition: { type: 'unique_cities', target: 6 },
    rewards: { xp: 10000, balance: 1000000, title: 'World Conqueror', badge: 'world_conqueror' },
    icon: '🗺️',
  },
  {
    id: 'geo_dubai',
    name: 'Dubai Dream',
    description: 'Own property in Dubai',
    category: 'geographic',
    difficulty: 'easy',
    type: 'permanent',
    order: 44,
    condition: { type: 'city_owned', cityName: 'Dubai', target: 1 },
    rewards: { xp: 200, balance: 20000 },
    icon: '🏙️',
  },
  {
    id: 'geo_london',
    name: 'London Calling',
    description: 'Own property in London',
    category: 'geographic',
    difficulty: 'easy',
    type: 'permanent',
    order: 45,
    condition: { type: 'city_owned', cityName: 'London', target: 1 },
    rewards: { xp: 200, balance: 20000 },
    icon: '🇬🇧',
  },

  // ─── DEVELOPMENT MISSIONS ───────────────────────────
  {
    id: 'dev_first',
    name: 'Builder',
    description: 'Complete your first development',
    category: 'development',
    difficulty: 'easy',
    type: 'permanent',
    order: 50,
    chainId: 'dev_chain',
    chainOrder: 1,
    condition: { type: 'total_construction_completed', target: 1 },
    rewards: { xp: 150, balance: 15000 },
    icon: '🔨',
  },
  {
    id: 'dev_10',
    name: 'Master Builder',
    description: 'Complete 10 developments',
    category: 'development',
    difficulty: 'medium',
    type: 'permanent',
    order: 51,
    chainId: 'dev_chain',
    chainOrder: 2,
    prerequisiteMissionId: 'dev_first',
    condition: { type: 'total_construction_completed', target: 10 },
    rewards: { xp: 500, balance: 75000 },
    icon: '🏗️',
  },
  {
    id: 'dev_25',
    name: 'Development Titan',
    description: 'Complete 25 developments',
    category: 'development',
    difficulty: 'hard',
    type: 'permanent',
    order: 52,
    chainId: 'dev_chain',
    chainOrder: 3,
    prerequisiteMissionId: 'dev_10',
    condition: { type: 'total_construction_completed', target: 25 },
    rewards: { xp: 2000, balance: 300000, title: 'Development Titan' },
    icon: '🏛️',
  },
  {
    id: 'dev_upgrade_5',
    name: 'Improver',
    description: 'Complete 5 upgrades',
    category: 'development',
    difficulty: 'easy',
    type: 'permanent',
    order: 53,
    chainId: 'upgrade_chain',
    chainOrder: 2,
    prerequisiteMissionId: 'first_upgrade',
    condition: { type: 'total_upgrades', target: 5 },
    rewards: { xp: 300, balance: 30000 },
    icon: '⬆️',
  },

  // ─── BANKING MISSIONS ───────────────────────────────
  {
    id: 'bank_first_loan',
    name: 'Borrower',
    description: 'Take out your first loan',
    category: 'banking',
    difficulty: 'easy',
    type: 'permanent',
    order: 60,
    chainId: 'bank_chain',
    chainOrder: 1,
    condition: { type: 'total_loans_taken', target: 1 },
    rewards: { xp: 100, balance: 10000 },
    icon: '🏦',
  },
  {
    id: 'bank_first_repay',
    name: 'Responsible Borrower',
    description: 'Make your first loan repayment',
    category: 'banking',
    difficulty: 'easy',
    type: 'permanent',
    order: 61,
    chainId: 'bank_chain',
    chainOrder: 2,
    prerequisiteMissionId: 'bank_first_loan',
    condition: { type: 'total_loan_repayments', target: 1 },
    rewards: { xp: 100, balance: 10000 },
    icon: '✅',
  },
  {
    id: 'bank_excellent_credit',
    name: 'Credit Champion',
    description: 'Maintain a credit score above 750',
    category: 'banking',
    difficulty: 'medium',
    type: 'permanent',
    order: 62,
    condition: { type: 'credit_score', target: 750 },
    rewards: { xp: 400, balance: 50000, badge: 'credit_champion' },
    icon: '⭐',
  },
  {
    id: 'bank_repay_10m',
    name: 'Debt Free King',
    description: 'Pay off $10M in total loan repayments',
    category: 'banking',
    difficulty: 'hard',
    type: 'permanent',
    order: 63,
    chainId: 'bank_chain',
    chainOrder: 3,
    prerequisiteMissionId: 'bank_first_repay',
    condition: { type: 'total_loan_amount_repaid', target: 10000000 },
    rewards: { xp: 2000, balance: 250000, title: 'Debt Free King' },
    icon: '👑',
  },

  // ─── AUCTION MISSIONS ───────────────────────────────
  {
    id: 'auction_win_10',
    name: 'Auction Master',
    description: 'Win 10 auctions',
    category: 'auction',
    difficulty: 'medium',
    type: 'permanent',
    order: 70,
    chainId: 'auction_chain',
    chainOrder: 2,
    prerequisiteMissionId: 'first_auction',
    condition: { type: 'auctions_won', target: 10 },
    rewards: { xp: 500, balance: 75000 },
    icon: '🏆',
  },
  {
    id: 'auction_sell',
    name: 'Auction Seller',
    description: 'Sell a property through auction',
    category: 'auction',
    difficulty: 'easy',
    type: 'permanent',
    order: 71,
    condition: { type: 'auctions_sold', target: 1 },
    rewards: { xp: 200, balance: 25000 },
    icon: '📤',
  },
  {
    id: 'auction_rare',
    name: 'Rare Finder',
    description: 'Win a Rare auction property',
    category: 'auction',
    difficulty: 'medium',
    type: 'permanent',
    order: 72,
    condition: { type: 'rare_auctions_won', target: 1 },
    rewards: { xp: 500, balance: 50000, badge: 'rare_finder' },
    icon: '💎',
  },
  {
    id: 'auction_win_25',
    name: 'Auction Legend',
    description: 'Win 25 auctions',
    category: 'auction',
    difficulty: 'expert',
    type: 'permanent',
    order: 73,
    chainId: 'auction_chain',
    chainOrder: 3,
    prerequisiteMissionId: 'auction_win_10',
    condition: { type: 'auctions_won', target: 25 },
    rewards: { xp: 5000, balance: 500000, title: 'Auction Legend', badge: 'auction_legend' },
    icon: '🏅',
  },

  // ─── COMPANY MISSIONS ───────────────────────────────
  {
    id: 'company_join',
    name: 'Team Player',
    description: 'Join a Real Estate Company',
    category: 'company',
    difficulty: 'easy',
    type: 'permanent',
    order: 80,
    chainId: 'company_chain',
    chainOrder: 1,
    condition: { type: 'joined_company', target: 1 },
    rewards: { xp: 150, balance: 15000 },
    icon: '🤝',
  },
  {
    id: 'company_create',
    name: 'Founder',
    description: 'Create your own Real Estate Company',
    category: 'company',
    difficulty: 'medium',
    type: 'permanent',
    order: 81,
    chainId: 'company_chain',
    chainOrder: 2,
    prerequisiteMissionId: 'company_join',
    condition: { type: 'created_company', target: 1 },
    rewards: { xp: 500, balance: 50000, title: 'Company Founder' },
    icon: '🏢',
  },
  {
    id: 'company_vote',
    name: 'Democrat',
    description: 'Participate in a company vote',
    category: 'company',
    difficulty: 'easy',
    type: 'permanent',
    order: 82,
    condition: { type: 'company_votes_cast', target: 1 },
    rewards: { xp: 100, balance: 10000 },
    icon: '🗳️',
  },
  {
    id: 'company_project',
    name: 'Company Achiever',
    description: 'Complete a company development project',
    category: 'company',
    difficulty: 'medium',
    type: 'permanent',
    order: 83,
    condition: { type: 'company_projects_completed', target: 1 },
    rewards: { xp: 400, balance: 40000 },
    icon: '📋',
  },
  {
    id: 'company_purchase',
    name: 'Company Investor',
    description: 'Purchase a property through your company',
    category: 'company',
    difficulty: 'medium',
    type: 'permanent',
    order: 84,
    condition: { type: 'company_properties_purchased', target: 1 },
    rewards: { xp: 300, balance: 30000 },
    icon: '🏢',
  },

  // ─── DISTRICT MISSIONS ──────────────────────────────
  {
    id: 'district_10',
    name: 'District Explorer',
    description: 'Own property in 10 different districts',
    category: 'district',
    difficulty: 'medium',
    type: 'permanent',
    order: 90,
    condition: { type: 'unique_districts', target: 10 },
    rewards: { xp: 500, balance: 75000 },
    icon: '🗺️',
  },
  {
    id: 'district_influence',
    name: 'District Power',
    description: 'Become the largest investor in a district',
    category: 'district',
    difficulty: 'hard',
    type: 'permanent',
    order: 91,
    condition: { type: 'district_leader', target: 1 },
    rewards: { xp: 2000, balance: 200000, title: 'District Power', badge: 'district_leader' },
    icon: '👑',
  },

  // ─── MARKET INTELLIGENCE MISSIONS ───────────────────
  {
    id: 'mi_first_report',
    name: 'Analyst',
    description: 'Purchase your first market report',
    category: 'intelligence',
    difficulty: 'easy',
    type: 'permanent',
    order: 100,
    chainId: 'mi_chain',
    chainOrder: 1,
    condition: { type: 'reports_purchased', target: 1 },
    rewards: { xp: 100, balance: 10000 },
    icon: '📊',
  },
  {
    id: 'mi_accuracy',
    name: 'Prophet',
    description: 'Reach 90% forecast accuracy on a report',
    category: 'intelligence',
    difficulty: 'hard',
    type: 'permanent',
    order: 101,
    condition: { type: 'forecast_accuracy_90', target: 1 },
    rewards: { xp: 2000, balance: 150000, title: 'Prophet', badge: 'prophet' },
    icon: '🔮',
  },
  {
    id: 'mi_20_reports',
    name: 'Market Guru',
    description: 'Purchase 20 market reports',
    category: 'intelligence',
    difficulty: 'medium',
    type: 'permanent',
    order: 102,
    chainId: 'mi_chain',
    chainOrder: 2,
    prerequisiteMissionId: 'mi_first_report',
    condition: { type: 'reports_purchased', target: 20 },
    rewards: { xp: 1000, balance: 100000, title: 'Market Guru' },
    icon: '📈',
  },

  // ─── DAILY MISSIONS ─────────────────────────────────
  {
    id: 'daily_collect_rent',
    name: 'Daily Collector',
    description: 'Collect rent today',
    category: 'daily',
    difficulty: 'easy',
    type: 'daily',
    order: 200,
    condition: { type: 'rent_collected_today', target: 1 },
    rewards: { xp: 30, balance: 3000 },
    icon: '📅',
  },
  {
    id: 'daily_bonus',
    name: 'Daily Bonus',
    description: 'Claim your daily bonus',
    category: 'daily',
    difficulty: 'easy',
    type: 'daily',
    order: 201,
    condition: { type: 'bonus_claimed_today', target: 1 },
    rewards: { xp: 20, balance: 2000 },
    icon: '🎁',
  },
  {
    id: 'daily_login',
    name: 'Daily Login',
    description: 'Login to the game today',
    category: 'daily',
    difficulty: 'easy',
    type: 'daily',
    order: 202,
    condition: { type: 'login_today', target: 1 },
    rewards: { xp: 10, balance: 1000 },
    icon: '🔑',
  },

  // ─── WEEKLY MISSIONS (scaled from daily) ────────────
  {
    id: 'weekly_collect_rent',
    name: 'Weekly Rent Collector',
    description: 'Collect rent 5 times this week',
    category: 'weekly',
    difficulty: 'medium',
    type: 'weekly',
    order: 210,
    condition: { type: 'rent_collected_this_week', target: 5 },
    rewards: { xp: 150, balance: 15000 },
    icon: '📆',
  },
  {
    id: 'weekly_bonus',
    name: 'Weekly Bonus Hunter',
    description: 'Claim your bonus 5 times this week',
    category: 'weekly',
    difficulty: 'medium',
    type: 'weekly',
    order: 211,
    condition: { type: 'bonus_claimed_this_week', target: 5 },
    rewards: { xp: 100, balance: 10000 },
    icon: '📆',
  },
  {
    id: 'weekly_login',
    name: 'Weekly Regular',
    description: 'Login 5 times this week',
    category: 'weekly',
    difficulty: 'medium',
    type: 'weekly',
    order: 212,
    condition: { type: 'login_count_this_week', target: 5 },
    rewards: { xp: 50, balance: 5000 },
    icon: '📆',
  },

  // ─── STOCK MARKET MISSIONS ────────────────────────────
  {
    id: 'stock_first_buy',
    name: 'First Trade',
    description: 'Buy your first stock',
    category: 'stocks',
    difficulty: 'easy',
    type: 'permanent',
    order: 110,
    condition: { type: 'stocks_bought', target: 1 },
    rewards: { xp: 100, balance: 10000 },
    icon: '📈',
  },
  {
    id: 'stock_first_dividend',
    name: 'Dividend Earner',
    description: 'Receive your first dividend payment',
    category: 'stocks',
    difficulty: 'medium',
    type: 'permanent',
    order: 111,
    condition: { type: 'dividends_received', target: 1 },
    rewards: { xp: 300, balance: 30000 },
    icon: '💵',
  },

  // ─── SOCIAL / COMMUNITY MISSIONS ──────────────────────
  {
    id: 'social_first_friend',
    name: 'Making Friends',
    description: 'Add your first friend',
    category: 'social',
    difficulty: 'easy',
    type: 'permanent',
    order: 300,
    condition: { type: 'friends_added', target: 1 },
    rewards: { xp: 50, balance: 1000 },
    icon: '🧑‍🤝‍🧑',
  },
  {
    id: 'social_3_friends',
    name: 'Social Circle',
    description: 'Add 3 friends',
    category: 'social',
    difficulty: 'easy',
    type: 'permanent',
    order: 301,
    condition: { type: 'friends_added', target: 3 },
    rewards: { xp: 100, balance: 3000 },
    icon: '👥',
  },
  {
    id: 'social_10_friends',
    name: 'Networker',
    description: 'Add 10 friends',
    category: 'social',
    difficulty: 'medium',
    type: 'permanent',
    order: 302,
    condition: { type: 'friends_added', target: 10 },
    rewards: { xp: 200, balance: 10000 },
    icon: '🤝',
  },
  {
    id: 'social_accept_request',
    name: 'Welcome In',
    description: 'Accept a friend request',
    category: 'social',
    difficulty: 'easy',
    type: 'permanent',
    order: 303,
    condition: { type: 'friend_requests_accepted', target: 1 },
    rewards: { xp: 50, balance: 1000 },
    icon: '✅',
  },
  {
    id: 'social_visit_profile',
    name: 'Getting Acquainted',
    description: 'Visit another player\u2019s profile',
    category: 'social',
    difficulty: 'easy',
    type: 'permanent',
    order: 304,
    condition: { type: 'profiles_visited', target: 1 },
    rewards: { xp: 25, balance: 500 },
    icon: '👀',
  },
  {
    id: 'social_visit_5_profiles',
    name: 'Community Scout',
    description: 'Visit 5 player profiles',
    category: 'social',
    difficulty: 'medium',
    type: 'permanent',
    order: 305,
    condition: { type: 'profiles_visited', target: 5 },
    rewards: { xp: 100, balance: 5000 },
    icon: '🔭',
  },
  {
    id: 'social_join_company',
    name: 'Team Player',
    description: 'Join a Real Estate Company',
    category: 'social',
    difficulty: 'easy',
    type: 'permanent',
    order: 306,
    condition: { type: 'joined_company', target: 1 },
    rewards: { xp: 75, balance: 2000 },
    icon: '🏢',
  },
  {
    id: 'social_invite_player',
    name: 'Recruiter',
    description: 'Invite another player to your company',
    category: 'social',
    difficulty: 'easy',
    type: 'permanent',
    order: 307,
    condition: { type: 'company_invites_sent', target: 1 },
    rewards: { xp: 75, balance: 2000 },
    icon: '📨',
  },
  {
    id: 'social_recruit_3',
    name: 'Growing Roster',
    description: 'Have 3 members in your company',
    category: 'social',
    difficulty: 'medium',
    type: 'permanent',
    order: 308,
    condition: { type: 'company_members_recruited', target: 3 },
    rewards: { xp: 200, balance: 7500 },
    icon: '🧑‍💼',
  },
  {
    id: 'social_company_vote',
    name: 'Voice in the Company',
    description: 'Participate in a company vote',
    category: 'social',
    difficulty: 'medium',
    type: 'permanent',
    order: 309,
    condition: { type: 'company_votes_cast', target: 1 },
    rewards: { xp: 100, balance: 3000 },
    icon: '🗳️',
  },
  {
    id: 'social_company_contract',
    name: 'Deal Closer',
    description: 'Complete a company contract',
    category: 'social',
    difficulty: 'hard',
    type: 'permanent',
    order: 310,
    condition: { type: 'company_contracts_completed', target: 1 },
    rewards: { xp: 400, balance: 15000 },
    icon: '📜',
  },

  // ─── MARKETPLACE MISSIONS ─────────────────────────────
  {
    id: 'market_list_property',
    name: 'Open House',
    description: 'List a property for sale',
    category: 'marketplace',
    difficulty: 'easy',
    type: 'permanent',
    order: 320,
    condition: { type: 'properties_listed', target: 1 },
    rewards: { xp: 75, balance: 2000 },
    icon: '🏷️',
  },
  {
    id: 'market_sell_5',
    name: 'Liquid Asset',
    description: 'Sell 5 properties',
    category: 'marketplace',
    difficulty: 'medium',
    type: 'permanent',
    order: 321,
    condition: { type: 'total_properties_sold', target: 5 },
    rewards: { xp: 200, balance: 10000 },
    icon: '💰',
  },
  {
    id: 'market_profit_sale',
    name: 'Sharp Dealer',
    description: 'Sell a property at a profit',
    category: 'marketplace',
    difficulty: 'medium',
    type: 'permanent',
    order: 322,
    condition: { type: 'property_sale_profit', target: 1 },
    rewards: { xp: 150, balance: 7500 },
    icon: '📈',
  },
  {
    id: 'market_profit_5_sales',
    name: 'Flipping Pro',
    description: 'Sell 5 properties at a profit',
    category: 'marketplace',
    difficulty: 'hard',
    type: 'permanent',
    order: 323,
    condition: { type: 'property_sale_profit', target: 5 },
    rewards: { xp: 500, balance: 25000 },
    icon: '🔁',
  },
  {
    id: 'market_property_value_1m',
    name: 'Portfolio Value',
    description: 'Own properties worth $1,000,000 total',
    category: 'marketplace',
    difficulty: 'medium',
    type: 'permanent',
    order: 324,
    condition: { type: 'property_value', target: 1000000 },
    rewards: { xp: 200, balance: 10000 },
    icon: '🏘️',
  },
  {
    id: 'market_property_value_10m',
    name: 'Property Baron',
    description: 'Own properties worth $10,000,000 total',
    category: 'marketplace',
    difficulty: 'hard',
    type: 'permanent',
    order: 325,
    condition: { type: 'property_value', target: 10000000 },
    rewards: { xp: 800, balance: 50000 },
    icon: '🏰',
  },

  // ─── STOCK MARKET MISSIONS ────────────────────────────
  {
    id: 'stock_3_companies',
    name: 'Diversified',
    description: 'Hold stocks in 3 different companies',
    category: 'stocks',
    difficulty: 'medium',
    type: 'permanent',
    order: 330,
    condition: { type: 'stocks_owned_companies', target: 3 },
    rewards: { xp: 200, balance: 10000 },
    icon: '📊',
  },
  {
    id: 'stock_make_profit',
    name: 'Market Winner',
    description: 'Make $10,000 in profit from stocks',
    category: 'stocks',
    difficulty: 'medium',
    type: 'permanent',
    order: 331,
    condition: { type: 'stock_profit', target: 10000 },
    rewards: { xp: 250, balance: 15000 },
    icon: '💹',
  },
  {
    id: 'stock_big_profit',
    name: 'Market Mogul',
    description: 'Make $100,000 in profit from stocks',
    category: 'stocks',
    difficulty: 'hard',
    type: 'permanent',
    order: 332,
    condition: { type: 'stock_profit', target: 100000 },
    rewards: { xp: 750, balance: 50000 },
    icon: '🏦',
  },
  {
    id: 'stock_ipo_shares',
    name: 'Going Public',
    description: 'Buy shares in a public (IPO) company',
    category: 'stocks',
    difficulty: 'hard',
    type: 'permanent',
    order: 333,
    condition: { type: 'ipo_shares_bought', target: 1 },
    rewards: { xp: 400, balance: 25000 },
    icon: '🎯',
  },

  // ─── EXPLORATION MISSIONS ─────────────────────────────
  {
    id: 'explore_city_3',
    name: 'City Hopper',
    description: 'Visit 3 cities',
    category: 'exploration',
    difficulty: 'easy',
    type: 'permanent',
    order: 340,
    condition: { type: 'city_visits', target: 3 },
    rewards: { xp: 75, balance: 2500 },
    icon: '🌆',
  },
  {
    id: 'explore_city_8',
    name: 'World Traveler',
    description: 'Visit 8 cities',
    category: 'exploration',
    difficulty: 'medium',
    type: 'permanent',
    order: 341,
    condition: { type: 'city_visits', target: 8 },
    rewards: { xp: 200, balance: 10000 },
    icon: '🌍',
  },
  {
    id: 'explore_districts_5',
    name: 'Neighborhood Explorer',
    description: 'Visit 5 districts',
    category: 'exploration',
    difficulty: 'easy',
    type: 'permanent',
    order: 342,
    condition: { type: 'district_visits', target: 5 },
    rewards: { xp: 75, balance: 2500 },
    icon: '🗺️',
  },
  {
    id: 'explore_countries_3',
    name: 'International Investor',
    description: 'Own properties in 3 different countries',
    category: 'exploration',
    difficulty: 'medium',
    type: 'permanent',
    order: 343,
    condition: { type: 'countries_owned', target: 3 },
    rewards: { xp: 250, balance: 12500 },
    icon: '🧳',
  },
  {
    id: 'explore_countries_6',
    name: 'Globetrotter',
    description: 'Own properties in 6 different countries',
    category: 'exploration',
    difficulty: 'hard',
    type: 'permanent',
    order: 344,
    condition: { type: 'countries_owned', target: 6 },
    rewards: { xp: 750, balance: 40000, title: 'Globetrotter' },
    icon: '✈️',
  },
  {
    id: 'explore_market_report',
    name: 'Market Analyst',
    description: 'View a city market report',
    category: 'exploration',
    difficulty: 'easy',
    type: 'permanent',
    order: 345,
    condition: { type: 'reports_purchased', target: 1 },
    rewards: { xp: 75, balance: 2500 },
    icon: '📊',
  },
  {
    id: 'explore_5_reports',
    name: 'Research Desk',
    description: 'View 5 market reports',
    category: 'exploration',
    difficulty: 'medium',
    type: 'permanent',
    order: 346,
    condition: { type: 'reports_purchased', target: 5 },
    rewards: { xp: 200, balance: 10000 },
    icon: '🔍',
  },

  // ─── COMPANY MISSIONS ─────────────────────────────────
  {
    id: 'company_hire_employee',
    name: 'First Hire',
    description: 'Hire your first company employee',
    category: 'company',
    difficulty: 'medium',
    type: 'permanent',
    order: 350,
    condition: { type: 'company_employees_hired', target: 1 },
    rewards: { xp: 150, balance: 7500 },
    icon: '👔',
  },
  {
    id: 'company_take_loan',
    name: 'Company Credit',
    description: 'Take a company loan',
    category: 'company',
    difficulty: 'medium',
    type: 'permanent',
    order: 351,
    condition: { type: 'company_loans_taken', target: 1 },
    rewards: { xp: 200, balance: 10000 },
    icon: '🏦',
  },
  {
    id: 'company_recruit_5',
    name: 'Five-Strong',
    description: 'Have 5 members in your company',
    category: 'company',
    difficulty: 'hard',
    type: 'permanent',
    order: 352,
    condition: { type: 'company_members_recruited', target: 5 },
    rewards: { xp: 400, balance: 20000 },
    icon: '🧑‍🤝‍🧑',
  },
  {
    id: 'company_ipo',
    name: 'IPO Founder',
    description: 'Take your company public through an IPO',
    category: 'company',
    difficulty: 'hard',
    type: 'permanent',
    order: 353,
    condition: { type: 'company_ipo_listed', target: 1 },
    rewards: { xp: 1500, balance: 150000, title: 'IPO Founder' },
    icon: '🚀',
  },

  // ─── ENGAGEMENT MISSIONS ──────────────────────────────
  {
    id: 'engage_login_streak_3',
    name: 'Getting in the Habit',
    description: 'Login 3 days in a row',
    category: 'engagement',
    difficulty: 'easy',
    type: 'permanent',
    order: 360,
    condition: { type: 'login_streak', target: 3 },
    rewards: { xp: 50, balance: 2000 },
    icon: '🔥',
  },
  {
    id: 'engage_login_streak_7',
    name: 'Weekly Devotion',
    description: 'Login 7 days in a row',
    category: 'engagement',
    difficulty: 'medium',
    type: 'permanent',
    order: 361,
    condition: { type: 'login_streak', target: 7 },
    rewards: { xp: 200, balance: 10000 },
    icon: '⚡',
  },
  {
    id: 'engage_login_streak_14',
    name: 'True Believer',
    description: 'Login 14 days in a row',
    category: 'engagement',
    difficulty: 'hard',
    type: 'permanent',
    order: 362,
    condition: { type: 'login_streak', target: 14 },
    rewards: { xp: 600, balance: 35000, badge: 'loyal_player' },
    icon: '💎',
  },
  {
    id: 'engage_complete_3',
    name: 'On a Roll',
    description: 'Complete 3 missions',
    category: 'engagement',
    difficulty: 'easy',
    type: 'permanent',
    order: 363,
    condition: { type: 'missions_completed', target: 3 },
    rewards: { xp: 100, balance: 3000 },
    icon: '🎯',
  },
  {
    id: 'engage_achievement',
    name: 'First Trophy',
    description: 'Unlock an achievement',
    category: 'engagement',
    difficulty: 'easy',
    type: 'permanent',
    order: 364,
    condition: { type: 'achievements_unlocked', target: 1 },
    rewards: { xp: 75, balance: 2500 },
    icon: '🏆',
  },
  {
    id: 'engage_rent_3',
    name: 'Landlord Routine',
    description: 'Collect rent 3 times',
    category: 'engagement',
    difficulty: 'easy',
    type: 'permanent',
    order: 365,
    condition: { type: 'total_rent_collected', target: 3 },
    rewards: { xp: 75, balance: 2500 },
    icon: '🏠',
  },
  {
    id: 'engage_check_market',
    name: 'Market Watcher',
    description: 'Check the marketplace 5 times',
    category: 'engagement',
    difficulty: 'easy',
    type: 'permanent',
    order: 366,
    condition: { type: 'market_visits', target: 5 },
    rewards: { xp: 50, balance: 2000 },
    icon: '🛒',
  },

  // ─── PROPERTY / INCOME ADDITIONS ──────────────────────
  {
    id: 'property_first_improvement',
    name: 'Makeover',
    description: 'Complete your first property improvement',
    category: 'property',
    difficulty: 'easy',
    type: 'permanent',
    order: 370,
    condition: { type: 'property_improvements', target: 1 },
    rewards: { xp: 75, balance: 5000 },
    icon: '🏗️',
  },
  {
    id: 'income_rent_100k',
    name: 'Rental Income',
    description: 'Collect $100,000 in total rent',
    category: 'income',
    difficulty: 'medium',
    type: 'permanent',
    order: 371,
    condition: { type: 'rent_total_earned', target: 100000 },
    rewards: { xp: 200, balance: 15000 },
    icon: '💵',
  },

  // ─── DAILY CHALLENGES ─────────────────────────────────
  {
    id: 'daily_profile_visit',
    name: 'Daily Scout',
    description: 'Visit a player profile today',
    category: 'daily',
    difficulty: 'easy',
    type: 'daily',
    order: 400,
    condition: { type: 'views_today', target: 1 },
    rewards: { xp: 20, balance: 1000 },
    icon: '👀',
  },
  {
    id: 'daily_check_market',
    name: 'Daily Market Check',
    description: 'Check the marketplace today',
    category: 'daily',
    difficulty: 'easy',
    type: 'daily',
    order: 401,
    condition: { type: 'market_visits_today', target: 1 },
    rewards: { xp: 20, balance: 1000 },
    icon: '🛒',
  },
  {
    id: 'daily_stock_trade',
    name: 'Daily Trade',
    description: 'Buy or sell stocks today',
    category: 'daily',
    difficulty: 'easy',
    type: 'daily',
    order: 402,
    condition: { type: 'stock_trades_today', target: 1 },
    rewards: { xp: 25, balance: 1500 },
    icon: '📈',
  },

  // ─── WEEKLY CHALLENGES ────────────────────────────────
  {
    id: 'weekly_stock_trades',
    name: 'Weekly Trader',
    description: 'Buy or sell stocks 5 times this week',
    category: 'weekly',
    difficulty: 'medium',
    type: 'weekly',
    order: 410,
    condition: { type: 'stock_trades_this_week', target: 5 },
    rewards: { xp: 100, balance: 10000 },
    icon: '📈',
  },
  {
    id: 'weekly_visits',
    name: 'Weekly Explorer',
    description: 'Visit 5 profiles, cities or districts this week',
    category: 'weekly',
    difficulty: 'medium',
    type: 'weekly',
    order: 411,
    condition: { type: 'views_this_week', target: 5 },
    rewards: { xp: 100, balance: 10000 },
    icon: '🗺️',
  },
  {
    id: 'weekly_auction_bids',
    name: 'Weekly Bidder',
    description: 'Place 2 auction bids this week',
    category: 'weekly',
    difficulty: 'medium',
    type: 'weekly',
    order: 412,
    condition: { type: 'auction_bids_this_week', target: 2 },
    rewards: { xp: 100, balance: 10000 },
    icon: '🔨',
  },

  // ─── CHAIN 1: FIRST PROPERTY EMPIRE ───────────────────
  {
    id: 'chain1_step1_acquire',
    name: 'Property Empire — Acquire',
    description: 'Purchase your first property',
    category: 'property',
    difficulty: 'medium',
    type: 'permanent',
    order: 500,
    chainId: 'chain_property_empire',
    chainOrder: 1,
    unlockLevel: 3,
    condition: { type: 'properties_owned', target: 1 },
    rewards: { xp: 100, balance: 5000 },
    icon: '🏠',
  },
  {
    id: 'chain1_step2_improve',
    name: 'Property Empire — Improve',
    description: 'Upgrade one of your properties',
    category: 'development',
    difficulty: 'medium',
    type: 'permanent',
    order: 501,
    chainId: 'chain_property_empire',
    chainOrder: 2,
    prerequisiteMissionId: 'chain1_step1_acquire',
    condition: { type: 'total_upgrades', target: 1 },
    rewards: { xp: 150, balance: 7500 },
    icon: '🔧',
  },
  {
    id: 'chain1_step3_earn',
    name: 'Property Empire — Earn',
    description: 'Collect rent from one property',
    category: 'income',
    difficulty: 'medium',
    type: 'permanent',
    order: 502,
    chainId: 'chain_property_empire',
    chainOrder: 3,
    prerequisiteMissionId: 'chain1_step2_improve',
    condition: { type: 'total_rent_collected', target: 1 },
    rewards: { xp: 200, balance: 10000 },
    icon: '💰',
  },
  {
    id: 'chain1_step4_portfolio',
    name: 'Property Empire — Portfolio',
    description: 'Own 3 properties simultaneously',
    category: 'property',
    difficulty: 'hard',
    type: 'permanent',
    order: 503,
    chainId: 'chain_property_empire',
    chainOrder: 4,
    prerequisiteMissionId: 'chain1_step3_earn',
    condition: { type: 'properties_owned', target: 3 },
    rewards: { xp: 500, balance: 25000 },
    icon: '🏘️',
  },

  // ─── CHAIN 2: AUCTION APPRENTICE ──────────────────────
  {
    id: 'chain2_step1_watch',
    name: 'Auction Apprentice — Watch',
    description: 'Watch an auction',
    category: 'auction',
    difficulty: 'easy',
    type: 'permanent',
    order: 510,
    chainId: 'chain_auction_apprentice',
    chainOrder: 1,
    unlockLevel: 3,
    condition: { type: 'auctions_watched', target: 1 },
    rewards: { xp: 50, balance: 2500 },
    icon: '👁️',
  },
  {
    id: 'chain2_step2_bid',
    name: 'Auction Apprentice — Bid',
    description: 'Place a valid auction bid',
    category: 'auction',
    difficulty: 'medium',
    type: 'permanent',
    order: 511,
    chainId: 'chain_auction_apprentice',
    chainOrder: 2,
    prerequisiteMissionId: 'chain2_step1_watch',
    condition: { type: 'auction_bids_placed', target: 1 },
    rewards: { xp: 100, balance: 5000 },
    icon: '🔨',
  },
  {
    id: 'chain2_step3_compete',
    name: 'Auction Apprentice — Compete',
    description: 'Bid in an auction where another player also bid',
    category: 'auction',
    difficulty: 'medium',
    type: 'permanent',
    order: 512,
    chainId: 'chain_auction_apprentice',
    chainOrder: 3,
    prerequisiteMissionId: 'chain2_step2_bid',
    condition: { type: 'auction_competitions', target: 1 },
    rewards: { xp: 200, balance: 10000 },
    icon: '⚔️',
  },
  {
    id: 'chain2_step4_win',
    name: 'Auction Apprentice — Win',
    description: 'Win an auction',
    category: 'auction',
    difficulty: 'hard',
    type: 'permanent',
    order: 513,
    chainId: 'chain_auction_apprentice',
    chainOrder: 4,
    prerequisiteMissionId: 'chain2_step3_compete',
    condition: { type: 'auctions_won', target: 1 },
    rewards: { xp: 600, balance: 30000 },
    icon: '🏆',
  },

  // ─── CHAIN 3: CORPORATE FOUNDER ───────────────────────
  {
    id: 'chain3_step1_create',
    name: 'Corporate Founder — Create',
    description: 'Create or join a Real Estate Company',
    category: 'company',
    difficulty: 'medium',
    type: 'permanent',
    order: 520,
    chainId: 'chain_corporate_founder',
    chainOrder: 1,
    unlockLevel: 12,
    condition: { type: 'joined_company', target: 1 },
    rewards: { xp: 300, balance: 15000 },
    icon: '🏢',
  },
  {
    id: 'chain3_step2_build',
    name: 'Corporate Founder — Build Together',
    description: 'Have your company own at least 2 properties',
    category: 'company',
    difficulty: 'hard',
    type: 'permanent',
    order: 521,
    chainId: 'chain_corporate_founder',
    chainOrder: 2,
    prerequisiteMissionId: 'chain3_step1_create',
    condition: { type: 'company_properties_purchased', target: 2 },
    rewards: { xp: 400, balance: 20000 },
    icon: '🏗️',
  },
  {
    id: 'chain3_step3_operate',
    name: 'Corporate Founder — Operate',
    description: 'Fully staff one company property',
    category: 'company',
    difficulty: 'hard',
    type: 'permanent',
    order: 522,
    chainId: 'chain_corporate_founder',
    chainOrder: 3,
    prerequisiteMissionId: 'chain3_step2_build',
    condition: { type: 'staffed_company_properties', target: 1 },
    rewards: { xp: 500, balance: 25000 },
    icon: '👔',
  },
  {
    id: 'chain3_step4_grow',
    name: 'Corporate Founder — Grow',
    description: 'Reach Company Level 10',
    category: 'company',
    difficulty: 'expert',
    type: 'permanent',
    order: 523,
    chainId: 'chain_corporate_founder',
    chainOrder: 4,
    prerequisiteMissionId: 'chain3_step3_operate',
    condition: { type: 'company_level', target: 10 },
    rewards: { xp: 1000, balance: 50000 },
    icon: '🌟',
  },

  // ─── CHAIN 4: CORPORATE AUCTION ───────────────────────
  {
    id: 'chain4_step1_proposal',
    name: 'Corporate Auction — Proposal',
    description: 'Submit a company auction proposal',
    category: 'auction',
    difficulty: 'medium',
    type: 'permanent',
    order: 530,
    chainId: 'chain_corporate_auction',
    chainOrder: 1,
    unlockLevel: 10,
    condition: { type: 'joined_company', target: 1 },
    rewards: { xp: 200, balance: 10000 },
    icon: '📝',
  },
  {
    id: 'chain4_step2_approval',
    name: 'Corporate Auction — Approval',
    description: 'Get a company auction proposal approved',
    category: 'auction',
    difficulty: 'hard',
    type: 'permanent',
    order: 531,
    chainId: 'chain_corporate_auction',
    chainOrder: 2,
    prerequisiteMissionId: 'chain4_step1_proposal',
    condition: { type: 'company_votes_cast', target: 1 },
    rewards: { xp: 400, balance: 20000 },
    icon: '✅',
  },
  {
    id: 'chain4_step3_execute',
    name: 'Corporate Auction — Execute',
    description: 'Successfully execute a company auction bid',
    category: 'auction',
    difficulty: 'hard',
    type: 'permanent',
    order: 532,
    chainId: 'chain_corporate_auction',
    chainOrder: 3,
    prerequisiteMissionId: 'chain4_step2_approval',
    condition: { type: 'auction_bids_placed', target: 1 },
    rewards: { xp: 600, balance: 30000 },
    icon: '⚡',
  },
  {
    id: 'chain4_step4_acquisition',
    name: 'Corporate Auction — Acquisition',
    description: 'Win an auction using your company',
    category: 'auction',
    difficulty: 'expert',
    type: 'permanent',
    order: 533,
    chainId: 'chain_corporate_auction',
    chainOrder: 4,
    prerequisiteMissionId: 'chain4_step3_execute',
    condition: { type: 'company_auctions_won', target: 1 },
    rewards: { xp: 1500, balance: 75000 },
    icon: '🎯',
  },

  // ─── CHAIN 5: MARKET INVESTOR ─────────────────────────
  {
    id: 'chain5_step1_invest',
    name: 'Market Investor — Invest',
    description: 'Purchase shares in a company',
    category: 'stocks',
    difficulty: 'medium',
    type: 'permanent',
    order: 540,
    chainId: 'chain_market_investor',
    chainOrder: 1,
    unlockLevel: 8,
    condition: { type: 'stocks_bought', target: 1 },
    rewards: { xp: 200, balance: 10000 },
    icon: '📈',
  },
  {
    id: 'chain5_step2_position',
    name: 'Market Investor — Build Position',
    description: 'Own shares in 3 different companies',
    category: 'stocks',
    difficulty: 'hard',
    type: 'permanent',
    order: 541,
    chainId: 'chain_market_investor',
    chainOrder: 2,
    prerequisiteMissionId: 'chain5_step1_invest',
    condition: { type: 'stocks_owned_companies', target: 3 },
    rewards: { xp: 400, balance: 20000 },
    icon: '💼',
  },
  {
    id: 'chain5_step3_hold',
    name: 'Market Investor — Hold',
    description: 'Maintain a stock position for at least one world month',
    category: 'stocks',
    difficulty: 'hard',
    type: 'permanent',
    order: 542,
    chainId: 'chain_market_investor',
    chainOrder: 3,
    prerequisiteMissionId: 'chain5_step2_position',
    condition: { type: 'stock_positions_held_long', target: 1 },
    rewards: { xp: 500, balance: 25000 },
    icon: '💎',
  },
  {
    id: 'chain5_step4_dividend',
    name: 'Market Investor — Dividend',
    description: 'Receive a dividend',
    category: 'stocks',
    difficulty: 'hard',
    type: 'permanent',
    order: 543,
    chainId: 'chain_market_investor',
    chainOrder: 4,
    prerequisiteMissionId: 'chain5_step3_hold',
    condition: { type: 'dividends_received', target: 1 },
    rewards: { xp: 800, balance: 40000 },
    icon: '💸',
  },

  // ─── CHAIN 6: GLOBAL EXPLORER ─────────────────────────
  {
    id: 'chain6_step1_discover',
    name: 'Global Explorer — Discover',
    description: 'Explore your first district',
    category: 'exploration',
    difficulty: 'easy',
    type: 'permanent',
    order: 550,
    chainId: 'chain_global_explorer',
    chainOrder: 1,
    unlockLevel: 5,
    condition: { type: 'district_visits', target: 1 },
    rewards: { xp: 100, balance: 5000 },
    icon: '🧭',
  },
  {
    id: 'chain6_step2_expand',
    name: 'Global Explorer — Expand',
    description: 'Discover 3 different districts',
    category: 'exploration',
    difficulty: 'medium',
    type: 'permanent',
    order: 551,
    chainId: 'chain_global_explorer',
    chainOrder: 2,
    prerequisiteMissionId: 'chain6_step1_discover',
    condition: { type: 'district_visits', target: 3 },
    rewards: { xp: 300, balance: 15000 },
    icon: '🗺️',
  },
  {
    id: 'chain6_step3_global',
    name: 'Global Explorer — Global',
    description: 'Own properties in 3 different cities',
    category: 'geographic',
    difficulty: 'hard',
    type: 'permanent',
    order: 552,
    chainId: 'chain_global_explorer',
    chainOrder: 3,
    prerequisiteMissionId: 'chain6_step2_expand',
    condition: { type: 'unique_cities', target: 3 },
    rewards: { xp: 600, balance: 30000 },
    icon: '🌍',
  },
  {
    id: 'chain6_step4_traveler',
    name: 'Global Explorer — World Traveler',
    description: 'Own properties in 5 different cities',
    category: 'geographic',
    difficulty: 'expert',
    type: 'permanent',
    order: 553,
    chainId: 'chain_global_explorer',
    chainOrder: 4,
    prerequisiteMissionId: 'chain6_step3_global',
    condition: { type: 'unique_cities', target: 5 },
    rewards: { xp: 1000, balance: 50000 },
    icon: '✈️',
  },

  // ─── CHAIN 7: PROPERTY MOGUL ──────────────────────────
  {
    id: 'chain7_step1_upgrade',
    name: 'Property Mogul — Upgrade',
    description: 'Complete 3 property upgrades',
    category: 'development',
    difficulty: 'hard',
    type: 'permanent',
    order: 560,
    chainId: 'chain_property_mogul',
    chainOrder: 1,
    unlockLevel: 15,
    condition: { type: 'total_upgrades', target: 3 },
    rewards: { xp: 400, balance: 20000 },
    icon: '🔨',
  },
  {
    id: 'chain7_step2_premium',
    name: 'Property Mogul — Premium Portfolio',
    description: 'Own 5 upgraded properties',
    category: 'development',
    difficulty: 'expert',
    type: 'permanent',
    order: 561,
    chainId: 'chain_property_mogul',
    chainOrder: 2,
    prerequisiteMissionId: 'chain7_step1_upgrade',
    condition: { type: 'properties_owned', target: 5 },
    rewards: { xp: 800, balance: 40000 },
    icon: '💎',
  },
  {
    id: 'chain7_step3_value',
    name: 'Property Mogul — Value Creator',
    description: 'Increase your portfolio value by $500,000 through development',
    category: 'development',
    difficulty: 'expert',
    type: 'permanent',
    order: 562,
    chainId: 'chain_property_mogul',
    chainOrder: 3,
    prerequisiteMissionId: 'chain7_step2_premium',
    condition: { type: 'total_portfolio_value', target: 500000 },
    rewards: { xp: 1000, balance: 50000 },
    icon: '📊',
  },
  {
    id: 'chain7_step4_tycoon',
    name: 'Property Mogul — Tycoon',
    description: 'Own a property portfolio worth at least $2,000,000',
    category: 'networth',
    difficulty: 'legendary',
    type: 'permanent',
    order: 563,
    chainId: 'chain_property_mogul',
    chainOrder: 4,
    prerequisiteMissionId: 'chain7_step3_value',
    condition: { type: 'total_portfolio_value', target: 2000000 },
    rewards: { xp: 2000, balance: 100000 },
    icon: '👑',
  },

  // ─── CHAIN 8: GLOBAL REAL ESTATE EMPIRE ────────────────
  {
    id: 'chain8_step1_diversify',
    name: 'Global Empire — Diversify',
    description: 'Own real estate and stocks simultaneously',
    category: 'marketplace',
    difficulty: 'hard',
    type: 'permanent',
    order: 570,
    chainId: 'chain_global_empire',
    chainOrder: 1,
    unlockLevel: 20,
    condition: { type: 'stocks_owned_companies', target: 1 },
    rewards: { xp: 1000, balance: 50000 },
    icon: '🌐',
  },
  {
    id: 'chain8_step2_expansion',
    name: 'Global Empire — Corporate Expansion',
    description: 'Have your company own properties in 2 different cities',
    category: 'company',
    difficulty: 'expert',
    type: 'permanent',
    order: 571,
    chainId: 'chain_global_empire',
    chainOrder: 2,
    prerequisiteMissionId: 'chain8_step1_diversify',
    condition: { type: 'company_properties_in_cities', target: 2 },
    rewards: { xp: 1500, balance: 75000 },
    icon: '🏙️',
  },
  {
    id: 'chain8_step3_empire',
    name: 'Global Empire — Auction Empire',
    description: 'Win an auction using your company',
    category: 'auction',
    difficulty: 'expert',
    type: 'permanent',
    order: 572,
    chainId: 'chain_global_empire',
    chainOrder: 3,
    prerequisiteMissionId: 'chain8_step2_expansion',
    condition: { type: 'company_auctions_won', target: 1 },
    rewards: { xp: 2000, balance: 100000 },
    icon: '🏆',
  },
  {
    id: 'chain8_step4_power',
    name: 'Global Empire — Market Power',
    description: 'Receive a dividend while your company owns at least 3 properties',
    category: 'stocks',
    difficulty: 'expert',
    type: 'permanent',
    order: 573,
    chainId: 'chain_global_empire',
    chainOrder: 4,
    prerequisiteMissionId: 'chain8_step3_empire',
    condition: { type: 'dividend_with_company_properties', target: 1 },
    rewards: { xp: 2000, balance: 100000 },
    icon: '💹',
  },
  {
    id: 'chain8_step5_ultimate',
    name: 'Global Empire — World Domination',
    description:
      'Own 10+ properties, 3+ cities, company with 5+ properties, stock positions in 3+ companies, auction win, and an upgrade',
    category: 'networth',
    difficulty: 'legendary',
    type: 'permanent',
    order: 574,
    chainId: 'chain_global_empire',
    chainOrder: 5,
    prerequisiteMissionId: 'chain8_step4_power',
    condition: { type: 'properties_owned', target: 10 },
    rewards: { xp: 5000, balance: 250000, badge: 'global_empire', title: 'Global Emperor' },
    icon: '👑',
  },
];

export const MISSION_CACHE_TTL = {
  list: 30,
  detail: 15,
  progress: 10,
  daily: 60,
  weekly: 120,
};

export function getMissionsByCategory(category) {
  return MISSION_DEFINITIONS.filter((m) => m.category === category && !m.hidden);
}

export function getMissionsByType(type) {
  return MISSION_DEFINITIONS.filter((m) => m.type === type && !m.hidden);
}

export function getMissionById(id) {
  return MISSION_DEFINITIONS.find((m) => m.id === id);
}

export function getChainMissions(chainId) {
  return MISSION_DEFINITIONS.filter((m) => m.chainId === chainId).sort((a, b) => a.chainOrder - b.chainOrder);
}

export function getVisibleMissions() {
  return MISSION_DEFINITIONS.filter((m) => !m.hidden);
}
