export const MISSION_CATEGORIES = [
  'beginner',
  'property',
  'income',
  'networth',
  'geographic',
  'development',
  'banking',
  'auction',
  'company',
  'district',
  'intelligence',
  'daily',
  'weekly',
  'seasonal',
  'event',
];

export const MISSION_DIFFICULTIES = {
  easy: { label: 'Easy', xpMultiplier: 1, balanceMultiplier: 1 },
  medium: { label: 'Medium', xpMultiplier: 2, balanceMultiplier: 2 },
  hard: { label: 'Hard', xpMultiplier: 4, balanceMultiplier: 4 },
  expert: { label: 'Expert', xpMultiplier: 8, balanceMultiplier: 8 },
  legendary: { label: 'Legendary', xpMultiplier: 16, balanceMultiplier: 16 },
};

export const MISSION_TYPES = ['permanent', 'daily', 'weekly', 'seasonal', 'event'];

export const MISSION_DEFINITIONS = [
  // ─── BEGINNER MISSIONS ───────────────────────────────
  {
    id: 'first_property',
    name: 'First Steps',
    description: 'Purchase your first property',
    category: 'beginner',
    difficulty: 'easy',
    type: 'permanent',
    order: 1,
    chainId: 'property_chain',
    chainOrder: 1,
    condition: { type: 'properties_owned', target: 1 },
    rewards: { xp: 50, balance: 5000 },
    icon: '🏠',
    unlocked: true,
  },
  {
    id: 'first_rent',
    name: 'Passive Income',
    description: 'Collect your first rent payment',
    category: 'beginner',
    difficulty: 'easy',
    type: 'permanent',
    order: 2,
    condition: { type: 'total_rent_collected', target: 1 },
    rewards: { xp: 50, balance: 5000 },
    icon: '💰',
    unlocked: true,
  },
  {
    id: 'first_upgrade',
    name: 'Renovation Rookie',
    description: 'Upgrade a property for the first time',
    category: 'beginner',
    difficulty: 'easy',
    type: 'permanent',
    order: 3,
    chainId: 'upgrade_chain',
    chainOrder: 1,
    condition: { type: 'total_upgrades', target: 1 },
    rewards: { xp: 75, balance: 7500 },
    icon: '🔧',
    unlocked: true,
  },
  {
    id: 'first_sell',
    name: 'Flipper',
    description: 'Sell your first property',
    category: 'beginner',
    difficulty: 'easy',
    type: 'permanent',
    order: 4,
    condition: { type: 'total_properties_sold', target: 1 },
    rewards: { xp: 75, balance: 10000 },
    icon: '💸',
    unlocked: true,
  },
  {
    id: 'first_auction',
    name: 'Auction Rookie',
    description: 'Purchase your first auction property',
    category: 'beginner',
    difficulty: 'easy',
    type: 'permanent',
    order: 5,
    chainId: 'auction_chain',
    chainOrder: 1,
    condition: { type: 'auctions_won', target: 1 },
    rewards: { xp: 100, balance: 15000 },
    icon: '🔨',
    unlocked: true,
  },

  // ─── PROPERTY MISSIONS ───────────────────────────────
  {
    id: 'own_5_properties',
    name: 'Small Portfolio',
    description: 'Own 5 properties',
    category: 'property',
    difficulty: 'easy',
    type: 'permanent',
    order: 10,
    chainId: 'property_chain',
    chainOrder: 2,
    prerequisiteMissionId: 'first_property',
    condition: { type: 'properties_owned', target: 5 },
    rewards: { xp: 200, balance: 25000 },
    icon: '🏘️',
  },
  {
    id: 'own_10_properties',
    name: 'Growing Empire',
    description: 'Own 10 properties',
    category: 'property',
    difficulty: 'medium',
    type: 'permanent',
    order: 11,
    chainId: 'property_chain',
    chainOrder: 3,
    prerequisiteMissionId: 'own_5_properties',
    condition: { type: 'properties_owned', target: 10 },
    rewards: { xp: 500, balance: 75000 },
    icon: '🏗️',
  },
  {
    id: 'own_25_properties',
    name: 'Real Estate Mogul',
    description: 'Own 25 properties',
    category: 'property',
    difficulty: 'hard',
    type: 'permanent',
    order: 12,
    chainId: 'property_chain',
    chainOrder: 4,
    prerequisiteMissionId: 'own_10_properties',
    condition: { type: 'properties_owned', target: 25 },
    rewards: { xp: 1500, balance: 250000, title: 'Mogul' },
    icon: '🏢',
  },
  {
    id: 'own_100_properties',
    name: 'Property Empire',
    description: 'Own 100 properties',
    category: 'property',
    difficulty: 'legendary',
    type: 'permanent',
    order: 13,
    chainId: 'property_chain',
    chainOrder: 5,
    prerequisiteMissionId: 'own_25_properties',
    condition: { type: 'properties_owned', target: 100 },
    rewards: { xp: 10000, balance: 2000000, title: 'Property Emperor', badge: 'property_empire' },
    icon: '👑',
  },
  {
    id: 'own_legendary_property',
    name: 'Legend Collector',
    description: 'Own a Legendary rated property',
    category: 'property',
    difficulty: 'medium',
    type: 'permanent',
    order: 14,
    condition: { type: 'own_legendary_property', target: 1 },
    rewards: { xp: 500, balance: 50000, badge: 'legend_collector' },
    icon: '⭐',
  },

  // ─── INCOME MISSIONS ────────────────────────────────
  {
    id: 'income_1k',
    name: 'Steady Earner',
    description: 'Reach $1,000 monthly income',
    category: 'income',
    difficulty: 'easy',
    type: 'permanent',
    order: 20,
    chainId: 'income_chain',
    chainOrder: 1,
    condition: { type: 'monthly_income', target: 1000 },
    rewards: { xp: 100, balance: 10000 },
    icon: '💵',
  },
  {
    id: 'income_10k',
    name: 'Rising Income',
    description: 'Reach $10,000 monthly income',
    category: 'income',
    difficulty: 'medium',
    type: 'permanent',
    order: 21,
    chainId: 'income_chain',
    chainOrder: 2,
    prerequisiteMissionId: 'income_1k',
    condition: { type: 'monthly_income', target: 10000 },
    rewards: { xp: 400, balance: 50000 },
    icon: '💶',
  },
  {
    id: 'income_100k',
    name: 'High Roller',
    description: 'Reach $100,000 monthly income',
    category: 'income',
    difficulty: 'hard',
    type: 'permanent',
    order: 22,
    chainId: 'income_chain',
    chainOrder: 3,
    prerequisiteMissionId: 'income_10k',
    condition: { type: 'monthly_income', target: 100000 },
    rewards: { xp: 1500, balance: 200000, title: 'High Roller' },
    icon: '💷',
  },
  {
    id: 'income_1m',
    name: "Millionaire's Income",
    description: 'Reach $1,000,000 monthly income',
    category: 'income',
    difficulty: 'expert',
    type: 'permanent',
    order: 23,
    chainId: 'income_chain',
    chainOrder: 4,
    prerequisiteMissionId: 'income_100k',
    condition: { type: 'monthly_income', target: 1000000 },
    rewards: { xp: 5000, balance: 1000000, title: 'Income Titan', badge: 'income_titan' },
    icon: '🏦',
  },

  // ─── NET WORTH MISSIONS ─────────────────────────────
  {
    id: 'networth_1m',
    name: 'Millionaire',
    description: 'Reach $1M net worth',
    category: 'networth',
    difficulty: 'easy',
    type: 'permanent',
    order: 30,
    chainId: 'networth_chain',
    chainOrder: 1,
    condition: { type: 'net_worth', target: 1000000 },
    rewards: { xp: 200, balance: 25000 },
    icon: '💎',
  },
  {
    id: 'networth_10m',
    name: 'Multi-Millionaire',
    description: 'Reach $10M net worth',
    category: 'networth',
    difficulty: 'medium',
    type: 'permanent',
    order: 31,
    chainId: 'networth_chain',
    chainOrder: 2,
    prerequisiteMissionId: 'networth_1m',
    condition: { type: 'net_worth', target: 10000000 },
    rewards: { xp: 1000, balance: 150000 },
    icon: '💰',
  },
  {
    id: 'networth_100m',
    name: 'Tycoon',
    description: 'Reach $100M net worth',
    category: 'networth',
    difficulty: 'hard',
    type: 'permanent',
    order: 32,
    chainId: 'networth_chain',
    chainOrder: 3,
    prerequisiteMissionId: 'networth_10m',
    condition: { type: 'net_worth', target: 100000000 },
    rewards: { xp: 5000, balance: 1000000, title: 'Tycoon' },
    icon: '🏆',
  },
  {
    id: 'networth_1b',
    name: 'Billionaire',
    description: 'Reach $1B net worth',
    category: 'networth',
    difficulty: 'legendary',
    type: 'permanent',
    order: 33,
    chainId: 'networth_chain',
    chainOrder: 4,
    prerequisiteMissionId: 'networth_100m',
    condition: { type: 'net_worth', target: 1000000000 },
    rewards: { xp: 20000, balance: 10000000, title: 'Billionaire', badge: 'billionaire' },
    icon: '🌐',
  },

  // ─── GEOGRAPHIC EXPANSION MISSIONS ──────────────────
  {
    id: 'geo_first_city',
    name: 'New Horizons',
    description: 'Own property in a different city',
    category: 'geographic',
    difficulty: 'easy',
    type: 'permanent',
    order: 40,
    condition: { type: 'unique_cities', target: 2 },
    rewards: { xp: 150, balance: 15000 },
    icon: '🌍',
  },
  {
    id: 'geo_3_cities',
    name: 'World Traveler',
    description: 'Own properties in 3 different cities',
    category: 'geographic',
    difficulty: 'medium',
    type: 'permanent',
    order: 41,
    chainId: 'geo_chain',
    chainOrder: 1,
    condition: { type: 'unique_cities', target: 3 },
    rewards: { xp: 500, balance: 50000, title: 'World Traveler' },
    icon: '✈️',
  },
  {
    id: 'geo_5_cities',
    name: 'Global Investor',
    description: 'Own properties in 5 different cities',
    category: 'geographic',
    difficulty: 'hard',
    type: 'permanent',
    order: 42,
    chainId: 'geo_chain',
    chainOrder: 2,
    prerequisiteMissionId: 'geo_3_cities',
    condition: { type: 'unique_cities', target: 5 },
    rewards: { xp: 1500, balance: 200000, title: 'Global Investor', badge: 'global_investor' },
    icon: '🌏',
  },
  {
    id: 'geo_all_cities',
    name: 'World Conqueror',
    description: 'Own properties in all cities',
    category: 'geographic',
    difficulty: 'legendary',
    type: 'permanent',
    order: 43,
    chainId: 'geo_chain',
    chainOrder: 3,
    prerequisiteMissionId: 'geo_5_cities',
    condition: { type: 'unique_cities', target: 6 },
    rewards: { xp: 10000, balance: 1000000, title: 'World Conqueror', badge: 'world_conqueror' },
    icon: '🗺️',
  },
  {
    id: 'geo_dubai',
    name: 'Dubai Dream',
    description: 'Own property in Dubai',
    category: 'geographic',
    difficulty: 'easy',
    type: 'permanent',
    order: 44,
    condition: { type: 'city_owned', cityName: 'Dubai', target: 1 },
    rewards: { xp: 200, balance: 20000 },
    icon: '🏙️',
  },
  {
    id: 'geo_london',
    name: 'London Calling',
    description: 'Own property in London',
    category: 'geographic',
    difficulty: 'easy',
    type: 'permanent',
    order: 45,
    condition: { type: 'city_owned', cityName: 'London', target: 1 },
    rewards: { xp: 200, balance: 20000 },
    icon: '🇬🇧',
  },

  // ─── DEVELOPMENT MISSIONS ───────────────────────────
  {
    id: 'dev_first',
    name: 'Builder',
    description: 'Complete your first development',
    category: 'development',
    difficulty: 'easy',
    type: 'permanent',
    order: 50,
    chainId: 'dev_chain',
    chainOrder: 1,
    condition: { type: 'total_construction_completed', target: 1 },
    rewards: { xp: 150, balance: 15000 },
    icon: '🔨',
  },
  {
    id: 'dev_10',
    name: 'Master Builder',
    description: 'Complete 10 developments',
    category: 'development',
    difficulty: 'medium',
    type: 'permanent',
    order: 51,
    chainId: 'dev_chain',
    chainOrder: 2,
    prerequisiteMissionId: 'dev_first',
    condition: { type: 'total_construction_completed', target: 10 },
    rewards: { xp: 500, balance: 75000 },
    icon: '🏗️',
  },
  {
    id: 'dev_25',
    name: 'Development Titan',
    description: 'Complete 25 developments',
    category: 'development',
    difficulty: 'hard',
    type: 'permanent',
    order: 52,
    chainId: 'dev_chain',
    chainOrder: 3,
    prerequisiteMissionId: 'dev_10',
    condition: { type: 'total_construction_completed', target: 25 },
    rewards: { xp: 2000, balance: 300000, title: 'Development Titan' },
    icon: '🏛️',
  },
  {
    id: 'dev_upgrade_5',
    name: 'Improver',
    description: 'Complete 5 upgrades',
    category: 'development',
    difficulty: 'easy',
    type: 'permanent',
    order: 53,
    chainId: 'upgrade_chain',
    chainOrder: 2,
    prerequisiteMissionId: 'first_upgrade',
    condition: { type: 'total_upgrades', target: 5 },
    rewards: { xp: 300, balance: 30000 },
    icon: '⬆️',
  },

  // ─── BANKING MISSIONS ───────────────────────────────
  {
    id: 'bank_first_loan',
    name: 'Borrower',
    description: 'Take out your first loan',
    category: 'banking',
    difficulty: 'easy',
    type: 'permanent',
    order: 60,
    chainId: 'bank_chain',
    chainOrder: 1,
    condition: { type: 'total_loans_taken', target: 1 },
    rewards: { xp: 100, balance: 10000 },
    icon: '🏦',
  },
  {
    id: 'bank_first_repay',
    name: 'Responsible Borrower',
    description: 'Make your first loan repayment',
    category: 'banking',
    difficulty: 'easy',
    type: 'permanent',
    order: 61,
    chainId: 'bank_chain',
    chainOrder: 2,
    prerequisiteMissionId: 'bank_first_loan',
    condition: { type: 'total_loan_repayments', target: 1 },
    rewards: { xp: 100, balance: 10000 },
    icon: '✅',
  },
  {
    id: 'bank_excellent_credit',
    name: 'Credit Champion',
    description: 'Maintain a credit score above 750',
    category: 'banking',
    difficulty: 'medium',
    type: 'permanent',
    order: 62,
    condition: { type: 'credit_score', target: 750 },
    rewards: { xp: 400, balance: 50000, badge: 'credit_champion' },
    icon: '⭐',
  },
  {
    id: 'bank_repay_10m',
    name: 'Debt Free King',
    description: 'Pay off $10M in total loan repayments',
    category: 'banking',
    difficulty: 'hard',
    type: 'permanent',
    order: 63,
    chainId: 'bank_chain',
    chainOrder: 3,
    prerequisiteMissionId: 'bank_first_repay',
    condition: { type: 'total_loan_amount_repaid', target: 10000000 },
    rewards: { xp: 2000, balance: 250000, title: 'Debt Free King' },
    icon: '👑',
  },

  // ─── AUCTION MISSIONS ───────────────────────────────
  {
    id: 'auction_win_10',
    name: 'Auction Master',
    description: 'Win 10 auctions',
    category: 'auction',
    difficulty: 'medium',
    type: 'permanent',
    order: 70,
    chainId: 'auction_chain',
    chainOrder: 2,
    prerequisiteMissionId: 'first_auction',
    condition: { type: 'auctions_won', target: 10 },
    rewards: { xp: 500, balance: 75000 },
    icon: '🏆',
  },
  {
    id: 'auction_sell',
    name: 'Auction Seller',
    description: 'Sell a property through auction',
    category: 'auction',
    difficulty: 'easy',
    type: 'permanent',
    order: 71,
    condition: { type: 'auctions_sold', target: 1 },
    rewards: { xp: 200, balance: 25000 },
    icon: '📤',
  },
  {
    id: 'auction_rare',
    name: 'Rare Finder',
    description: 'Win a Rare auction property',
    category: 'auction',
    difficulty: 'medium',
    type: 'permanent',
    order: 72,
    condition: { type: 'rare_auctions_won', target: 1 },
    rewards: { xp: 500, balance: 50000, badge: 'rare_finder' },
    icon: '💎',
  },
  {
    id: 'auction_win_25',
    name: 'Auction Legend',
    description: 'Win 25 auctions',
    category: 'auction',
    difficulty: 'expert',
    type: 'permanent',
    order: 73,
    chainId: 'auction_chain',
    chainOrder: 3,
    prerequisiteMissionId: 'auction_win_10',
    condition: { type: 'auctions_won', target: 25 },
    rewards: { xp: 5000, balance: 500000, title: 'Auction Legend', badge: 'auction_legend' },
    icon: '🏅',
  },

  // ─── COMPANY MISSIONS ───────────────────────────────
  {
    id: 'company_join',
    name: 'Team Player',
    description: 'Join a Real Estate Company',
    category: 'company',
    difficulty: 'easy',
    type: 'permanent',
    order: 80,
    chainId: 'company_chain',
    chainOrder: 1,
    condition: { type: 'joined_company', target: 1 },
    rewards: { xp: 150, balance: 15000 },
    icon: '🤝',
  },
  {
    id: 'company_create',
    name: 'Founder',
    description: 'Join a Real Estate Company',
    category: 'company',
    difficulty: 'medium',
    type: 'permanent',
    order: 81,
    chainId: 'company_chain',
    chainOrder: 2,
    prerequisiteMissionId: 'company_join',
    condition: { type: 'joined_company', target: 1 },
    rewards: { xp: 500, balance: 50000, title: 'Company Founder' },
    icon: '🏢',
  },
  {
    id: 'company_vote',
    name: 'Democrat',
    description: 'Participate in a company vote',
    category: 'company',
    difficulty: 'easy',
    type: 'permanent',
    order: 82,
    condition: { type: 'company_votes_cast', target: 1 },
    rewards: { xp: 100, balance: 10000 },
    icon: '🗳️',
  },
  {
    id: 'company_project',
    name: 'Company Achiever',
    description: 'Complete a company development project',
    category: 'company',
    difficulty: 'medium',
    type: 'permanent',
    order: 83,
    condition: { type: 'company_projects_completed', target: 1 },
    rewards: { xp: 400, balance: 40000 },
    icon: '📋',
  },
  {
    id: 'company_purchase',
    name: 'Company Investor',
    description: 'Purchase a property through your company',
    category: 'company',
    difficulty: 'medium',
    type: 'permanent',
    order: 84,
    condition: { type: 'company_properties_purchased', target: 1 },
    rewards: { xp: 300, balance: 30000 },
    icon: '🏢',
  },

  // ─── DISTRICT MISSIONS ──────────────────────────────
  {
    id: 'district_10',
    name: 'District Explorer',
    description: 'Own property in 10 different districts',
    category: 'district',
    difficulty: 'medium',
    type: 'permanent',
    order: 90,
    condition: { type: 'unique_districts', target: 10 },
    rewards: { xp: 500, balance: 75000 },
    icon: '🗺️',
  },
  {
    id: 'district_influence',
    name: 'District Power',
    description: 'Become the largest investor in a district',
    category: 'district',
    difficulty: 'hard',
    type: 'permanent',
    order: 91,
    condition: { type: 'district_leader', target: 1 },
    rewards: { xp: 2000, balance: 200000, title: 'District Power', badge: 'district_leader' },
    icon: '👑',
  },

  // ─── MARKET INTELLIGENCE MISSIONS ───────────────────
  {
    id: 'mi_first_report',
    name: 'Analyst',
    description: 'Purchase your first market report',
    category: 'intelligence',
    difficulty: 'easy',
    type: 'permanent',
    order: 100,
    chainId: 'mi_chain',
    chainOrder: 1,
    condition: { type: 'reports_purchased', target: 1 },
    rewards: { xp: 100, balance: 10000 },
    icon: '📊',
  },
  {
    id: 'mi_accuracy',
    name: 'Prophet',
    description: 'Reach 90% forecast accuracy on a report',
    category: 'intelligence',
    difficulty: 'hard',
    type: 'permanent',
    order: 101,
    condition: { type: 'forecast_accuracy_90', target: 1 },
    rewards: { xp: 2000, balance: 150000, title: 'Prophet', badge: 'prophet' },
    icon: '🔮',
  },
  {
    id: 'mi_20_reports',
    name: 'Market Guru',
    description: 'Purchase 20 market reports',
    category: 'intelligence',
    difficulty: 'medium',
    type: 'permanent',
    order: 102,
    chainId: 'mi_chain',
    chainOrder: 2,
    prerequisiteMissionId: 'mi_first_report',
    condition: { type: 'reports_purchased', target: 20 },
    rewards: { xp: 1000, balance: 100000, title: 'Market Guru' },
    icon: '📈',
  },

  // ─── DAILY MISSIONS ─────────────────────────────────
  {
    id: 'daily_collect_rent',
    name: 'Daily Collector',
    description: 'Collect rent today',
    category: 'daily',
    difficulty: 'easy',
    type: 'daily',
    order: 200,
    condition: { type: 'rent_collected_today', target: 1 },
    rewards: { xp: 30, balance: 3000 },
    icon: '📅',
  },
  {
    id: 'daily_bonus',
    name: 'Daily Bonus',
    description: 'Claim your daily bonus',
    category: 'daily',
    difficulty: 'easy',
    type: 'daily',
    order: 201,
    condition: { type: 'bonus_claimed_today', target: 1 },
    rewards: { xp: 20, balance: 2000 },
    icon: '🎁',
  },
  {
    id: 'daily_login',
    name: 'Daily Login',
    description: 'Login to the game today',
    category: 'daily',
    difficulty: 'easy',
    type: 'daily',
    order: 202,
    condition: { type: 'login_today', target: 1 },
    rewards: { xp: 10, balance: 1000 },
    icon: '🔑',
  },

  // ─── WEEKLY MISSIONS ────────────────────────────────
  {
    id: 'weekly_earn_100k',
    name: 'Weekly Earner',
    description: 'Earn $100,000 this week',
    category: 'weekly',
    difficulty: 'medium',
    type: 'weekly',
    order: 210,
    condition: { type: 'money_earned_this_week', target: 100000 },
    rewards: { xp: 300, balance: 30000 },
    icon: '📆',
  },
  {
    id: 'weekly_buy_5',
    name: 'Weekly Collector',
    description: 'Buy 5 properties this week',
    category: 'weekly',
    difficulty: 'medium',
    type: 'weekly',
    order: 211,
    condition: { type: 'properties_bought_this_week', target: 5 },
    rewards: { xp: 400, balance: 40000 },
    icon: '📆',
  },
  {
    id: 'weekly_win_auction',
    name: 'Weekly Champion',
    description: 'Win an auction this week',
    category: 'weekly',
    difficulty: 'medium',
    type: 'weekly',
    order: 212,
    condition: { type: 'auctions_won_this_week', target: 1 },
    rewards: { xp: 500, balance: 50000 },
    icon: '📆',
  },

  // ─── FUTURE / STOCK MARKET (placeholder) ────────────
  {
    id: 'stock_first_buy',
    name: 'First Trade',
    description: 'Buy your first stock',
    category: 'beginner',
    difficulty: 'easy',
    type: 'permanent',
    order: 110,
    condition: { type: 'stocks_bought', target: 1 },
    rewards: { xp: 100, balance: 10000 },
    icon: '📈',
    hidden: true,
  },
  {
    id: 'stock_first_dividend',
    name: 'Dividend Earner',
    description: 'Receive your first dividend payment',
    category: 'income',
    difficulty: 'medium',
    type: 'permanent',
    order: 111,
    condition: { type: 'dividends_received', target: 1 },
    rewards: { xp: 300, balance: 30000 },
    icon: '💵',
    hidden: true,
  },
];

export const MISSION_CACHE_TTL = {
  list: 30,
  detail: 15,
  progress: 10,
  daily: 60,
  weekly: 120,
};

export function getMissionsByCategory(category) {
  return MISSION_DEFINITIONS.filter((m) => m.category === category && !m.hidden);
}

export function getMissionsByType(type) {
  return MISSION_DEFINITIONS.filter((m) => m.type === type && !m.hidden);
}

export function getMissionById(id) {
  return MISSION_DEFINITIONS.find((m) => m.id === id);
}

export function getChainMissions(chainId) {
  return MISSION_DEFINITIONS.filter((m) => m.chainId === chainId).sort((a, b) => a.chainOrder - b.chainOrder);
}

export function getVisibleMissions() {
  return MISSION_DEFINITIONS.filter((m) => !m.hidden);
}
