export const INDUSTRIES = {
  technology: {
    id: 'technology',
    label: 'Technology',
    baseGrowthRate: 0.012,
    volatility: 0.04,
    demandMultiplier: 1.3,
    color: '#3b82f6',
    icon: '\uD83D\uDCBB',
    preferredCities: ['San Francisco', 'New York', 'London', 'Tel Aviv', 'Tokyo'],
  },
  finance: {
    id: 'finance',
    label: 'Finance',
    baseGrowthRate: 0.008,
    volatility: 0.03,
    demandMultiplier: 1.1,
    color: '#10b981',
    icon: '\uD83D\uDCB0',
    preferredCities: ['New York', 'London', 'Tokyo', 'Hong Kong', 'Singapore'],
  },
  manufacturing: {
    id: 'manufacturing',
    label: 'Manufacturing',
    baseGrowthRate: 0.005,
    volatility: 0.025,
    demandMultiplier: 1.0,
    color: '#f59e0b',
    icon: '\uD83C\uDFED',
    preferredCities: ['Detroit', 'Munich', 'Shanghai', 'Seoul', 'Houston'],
  },
  retail: {
    id: 'retail',
    label: 'Retail',
    baseGrowthRate: 0.006,
    volatility: 0.028,
    demandMultiplier: 0.9,
    color: '#ec4899',
    icon: '\uD83C\uDFEA',
    preferredCities: ['New York', 'London', 'Tokyo', 'Paris', 'Shanghai'],
  },
  energy: {
    id: 'energy',
    label: 'Energy',
    baseGrowthRate: 0.004,
    volatility: 0.035,
    demandMultiplier: 1.2,
    color: '#ef4444',
    icon: '\u26A1',
    preferredCities: ['Houston', 'Dubai', 'Riyadh', 'London', 'Beijing'],
  },
  healthcare: {
    id: 'healthcare',
    label: 'Healthcare',
    baseGrowthRate: 0.007,
    volatility: 0.02,
    demandMultiplier: 1.0,
    color: '#06b6d4',
    icon: '\uD83C\uDFE5',
    preferredCities: ['Boston', 'New York', 'London', 'Tokyo', 'Berlin'],
  },
  logistics: {
    id: 'logistics',
    label: 'Logistics',
    baseGrowthRate: 0.005,
    volatility: 0.022,
    demandMultiplier: 0.8,
    color: '#8b5cf6',
    icon: '\uD83D\uDCE6',
    preferredCities: ['Singapore', 'Rotterdam', 'Shanghai', 'Dubai', 'Los Angeles'],
  },
  entertainment: {
    id: 'entertainment',
    label: 'Entertainment',
    baseGrowthRate: 0.009,
    volatility: 0.045,
    demandMultiplier: 0.7,
    color: '#f97316',
    icon: '\uD83C\uDFAC',
    preferredCities: ['Los Angeles', 'New York', 'London', 'Tokyo', 'Seoul'],
  },
};

export const COMPANY_SIZES = {
  startup: { label: 'Startup', employees: [10, 50], revenue: [50000, 300000], sharePrice: [5, 25] },
  small: { label: 'Small', employees: [50, 200], revenue: [300000, 2000000], sharePrice: [15, 60] },
  medium: { label: 'Medium', employees: [200, 1000], revenue: [2000000, 15000000], sharePrice: [40, 150] },
  large: { label: 'Large', employees: [1000, 5000], revenue: [15000000, 100000000], sharePrice: [100, 500] },
  corporation: {
    label: 'Corporation',
    employees: [5000, 50000],
    revenue: [100000000, 1000000000],
    sharePrice: [200, 2000],
  },
};

export const COMPANY_NAME_PARTS = {
  technology: {
    prefixes: ['Nova', 'Cyber', 'Apex', 'Quantum', 'Vertex', 'Pulse', 'Nexus', 'Flux', 'Core', 'Edge'],
    suffixes: ['Tech', 'Labs', 'Systems', 'Digital', 'AI', 'Software', 'Dynamics', 'Logic', 'Data', 'Net'],
  },
  finance: {
    prefixes: ['Atlas', 'Summit', 'Crest', 'Pinnacle', 'Prime', 'Sterling', 'Vanguard', 'Apex', 'Elite', 'Capital'],
    suffixes: [
      'Capital',
      'Partners',
      'Group',
      'Holdings',
      'Fund',
      'Advisors',
      'Securities',
      'Trust',
      'Finance',
      'Wealth',
    ],
  },
  manufacturing: {
    prefixes: ['Iron', 'Steel', 'Titan', 'Forge', 'Apex', 'Global', 'Prime', 'Apex', 'Union', 'National'],
    suffixes: [
      'Industries',
      'Manufacturing',
      'Corp',
      'Works',
      'Fabrication',
      'Steel',
      'Metals',
      'Engineering',
      'Products',
      'MFG',
    ],
  },
  retail: {
    prefixes: ['Fresh', 'Prime', 'Grand', 'Metro', 'Urban', 'Luxe', 'Vibe', 'Core', 'Swift', 'Bright'],
    suffixes: ['Market', 'Mart', 'Store', 'Shop', 'Retail', 'Commerce', 'Outlets', 'Goods', 'Supplies', 'Co'],
  },
  energy: {
    prefixes: ['Solar', 'Thunder', 'Volt', 'Power', 'Hydro', 'Flame', 'Spark', 'Grid', 'Force', 'Ray'],
    suffixes: ['Energy', 'Power', 'Fuel', 'Oil', 'Gas', 'Utilities', 'Renewables', 'Corp', 'Energy Co', 'Power Co'],
  },
  healthcare: {
    prefixes: ['Vita', 'Med', 'Care', 'Life', 'Health', 'Cure', 'Well', 'Bio', 'Pharma', 'Nova'],
    suffixes: ['Health', 'Med', 'Pharma', 'Bio', 'Care', 'Wellness', 'Labs', 'Science', 'Medical', 'Therapeutics'],
  },
  logistics: {
    prefixes: ['Rapid', 'Swift', 'Atlas', 'Global', 'Prime', 'Apex', 'Express', 'Cargo', 'Fleet', 'Trans'],
    suffixes: [
      'Logistics',
      'Freight',
      'Shipping',
      'Transport',
      'Cargo',
      'Express',
      'Moving',
      'Lines',
      'Haulage',
      'Trans',
    ],
  },
  entertainment: {
    prefixes: ['Star', 'Dream', 'Vision', 'Epic', 'Saga', 'Nova', 'Cosmic', 'Flash', 'Blaze', 'Prism'],
    suffixes: [
      'Studios',
      'Entertainment',
      'Media',
      'Films',
      'Arts',
      'Works',
      'Productions',
      'Group',
      'Network',
      'Vision',
    ],
  },
};

export const STOCK_MARKET_CONFIG = {
  initialCompaniesPerCity: 2,
  maxCompaniesTotal: 100,
  sharesPerCompany: { min: 100000, max: 10000000 },
  priceUpdateSmoothing: 0.3,
  eventChancePerTick: 0.12,
  expansionChance: 0.4,
  relocationChance: 0.15,
  layoffChance: 0.2,
  growthChance: 0.25,
  bankruptcyChance: 0.05,
  minSharePrice: 1.0,
  maxSharePrice: 5000,
  historyMaxEntries: 120,
  marketSentimentChance: 0.08,
  sentimentDecay: 0.95,
};

export const COMPANY_EVENTS = {
  expansion: {
    employeeGrowth: [0.1, 0.3],
    revenueGrowth: [0.05, 0.2],
    priceImpact: [0.03, 0.1],
    cityDemandBoost: 0.05,
    cityPopulationBoost: 500,
  },
  relocation: {
    employeeLoss: [0.05, 0.15],
    revenueLoss: [0.03, 0.1],
    priceImpact: [-0.08, -0.02],
    sourceCityDemandDrop: -0.04,
    destCityDemandBoost: 0.06,
    sourcePopulationDrop: -300,
    destPopulationBoost: 400,
  },
  layoff: {
    employeeLoss: [0.1, 0.25],
    revenueLoss: [0.05, 0.15],
    priceImpact: [-0.1, -0.03],
    cityDemandDrop: -0.03,
  },
  growth: {
    employeeGrowth: [0.05, 0.15],
    revenueGrowth: [0.08, 0.2],
    priceImpact: [0.02, 0.08],
    cityDemandBoost: 0.02,
  },
  bankruptcy: {
    employeeLoss: 1.0,
    revenueLoss: 1.0,
    priceImpact: -0.5,
    cityDemandDrop: -0.08,
    cityPopulationDrop: -1000,
  },
};
